// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeUTPe-8wDfg8eVt_eeisBPFiwdX_wfN8',
    appId: '1:662924439138:web:f43ac915fa23fd41422b3b',
    messagingSenderId: '662924439138',
    projectId: 'social-media-test-app-bd16a',
    authDomain: 'social-media-test-app-bd16a.firebaseapp.com',
    storageBucket: 'social-media-test-app-bd16a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQJi76DVOWXD81COIdJlSAwzMnACy7T3c',
    appId: '1:662924439138:android:439c4292031d3e8c422b3b',
    messagingSenderId: '662924439138',
    projectId: 'social-media-test-app-bd16a',
    storageBucket: 'social-media-test-app-bd16a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuzYfp-T3eTL5Ec3At1OPElMSNIKpOUAQ',
    appId: '1:662924439138:ios:c79fea40863c9860422b3b',
    messagingSenderId: '662924439138',
    projectId: 'social-media-test-app-bd16a',
    storageBucket: 'social-media-test-app-bd16a.appspot.com',
    iosBundleId: 'com.example.club',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuzYfp-T3eTL5Ec3At1OPElMSNIKpOUAQ',
    appId: '1:662924439138:ios:c79fea40863c9860422b3b',
    messagingSenderId: '662924439138',
    projectId: 'social-media-test-app-bd16a',
    storageBucket: 'social-media-test-app-bd16a.appspot.com',
    iosBundleId: 'com.example.club',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeUTPe-8wDfg8eVt_eeisBPFiwdX_wfN8',
    appId: '1:662924439138:web:7fcfcd69dcf5466d422b3b',
    messagingSenderId: '662924439138',
    projectId: 'social-media-test-app-bd16a',
    authDomain: 'social-media-test-app-bd16a.firebaseapp.com',
    storageBucket: 'social-media-test-app-bd16a.appspot.com',
  );
}
